version: "3.7"

services:
  portracker:
donetick:
    image: donetick/donetick
    container_name: donetick
    restart: unless-stopped
    ports:
      - 2021:2021
    volumes:
      - ${APP_DATA_DIR}/donetick/data:/donetick-data
      - ${APP_DATA_DIR}/donetick/config:/config
    environment:
      - DT_ENV=selfhosted
      - DT_SQLITE_PATH=/donetick-data/donetick.db
